### ISSUE TITLE
Website: [Template] gather content for Template section

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#1011]
### Objective:

1. Document AEM templates's designs & usage 
2. Publish design assets for adopters to download and make their own pages

### Tasks

- [ ] Connect with stakeholders: Sandeep, Shawn Hoglund to find how the AEM team sees the guidance to the templates should be conveyed?
- [ ] Gather content for Template section
- [ ] Work on the page design
