### ISSUE TITLE
Project Pupa: Success measure criteria planning

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#1022]
### Objective:

Research and find out from SMEs (Linda and Jo Welsh) on how we can set success measure for Carbon for IBM.com website.

### Tasks:

- [x] Set up a call to meet with Linda for:
- Understand how we currently track the Carbon for IBM.com adoption and website traffic.
- Get recommendations from Linda on how we may set baselines for us to measure the success or outcome of this project.

- [x] Set up a call to meet with Jo for:
- Share project goal with Jo and get her SME recommendations on how we should set up a baseline for success measure.

- [x] Meet with Linda to share the plan for feedback.

### Acceptance criteria (The meaning of "Done")

- [x] Have a list of baseline setup options to share with Linda.
- [x] Align on what we are going to do for success measures for the project and future.

**Comment by JennySanchez** [comment]
**Task update:**
Meet with Linda on Tue 06/01/2021 to learn more about her point of view on Success measures.

**Next step:**
Will meet with Jo on Mon 06/07/2021.

**Comment by JennySanchez** [comment]
Based on the conversation with Jo, the two tools listed below are the tools for us to explore:

**Usabilla** is a tool owned by CIO. A designer called [Claud Elie](https://w3.ibm.com/bluepages/profile.html?uid=986894897) is the one we should reach out to to find out more. It's a tool acquired by IBM. The name of the tool might be something else. 

**Disqus** is a tool implemented on the IBM Doc website pages (in the page deeper into the website). Disqus is the tool to get input from the viewer on if the content on the page is helpful to them or not. This could be a tool for us to get feedback on website page content in the future.

**Comment by JennySanchez** [comment]
**Task update:** @IsiImoisi-ibm set up the call with Claud on CIO to learn more about the Usabilla now called GetFeedabck for Thursday at 11 am. We will know more about the tool and determine if that's the tool we should use.

**Comment by vinushad-ibm** [comment]
**Task Update:** Meeting with Claude Elie 
**Key Notes:**
- Usabilla does not have metrics on traffic like Google Analytics, but can provide metrics such as overall standing, NPS score, and goal completion percentage. 
- In order to sign up for Usabilla feature, must fill out this [form](https://www.surveygizmo.com/s3/4908645/Sign-up-my-application-for-VotE)
- Will provide a "feedback" button on all Carbon for IBM.com pages 
- Issue that came up: NPS score is more accurate if the sample size is large. Because Carbon for IBM.com does not get as many users, an email campaign/slack broadcast may be necessary to recruit participants to give feedback. 

**Next Steps**
- [ ] Confirm with Jen about feasibility of applying Usabilla to Carbon for IBM.com
- [ ] Fill out application form 
- [ ] Implement Usabilla on Carbon for IBM.com

**Comment by vinushad-ibm** [comment]
**Task Update:** Meeting with Linda 
**Key Notes:** 
- Met with Linda and got the green light to sign up for Usabilla for the Carbon for IBM.com website
