### ISSUE TITLE
Project Pupa: Project brand identity

### ISSUE THREAD

**Issue by maryjiang-ibm** [carbon-design-system/carbon-for-ibm-dotcom-website#1024]
### Objective:
Elevate Project Pupa's storytelling in playback presentation(s) with meaningful visual metaphors.

### Tasks:
- [x] Collect concept explorations on the [Mural](https://app.mural.co/t/dgcdesign5626/m/dgcdesign5626/1622060198460/9ac9b548f3f8c055b38571a48d429f67d6ddaceb?sender=uc3295538086ad1032fc24245) - ending EOD on Monday, June 7th

- [x] Visual explorations for illustrations

- [x] Visual explorations for logo

- [ ] Meet with fantastic four (Jenny S, Isi, Vinusha) to select final versions 

### Acceptance Criteria:

- [ ] Have exported image assets for the Project Pupa logomark

- [x] Source file demonstrating selected illustration style

**Comment by maryjiang-ibm** [comment]
Concept selected: Metamorphosis of the Carbon for dotcom website. "Taking the pieces of the website apart and building it back up". The current cupcake version = premature caterpillar; our reimagined version = pupa soon to be a butterfly.

Visual style of the logo will be elegant, incorporating transparency and simple geometry.

**Comment by JennySanchez** [comment]
@marcJV Can you add the link to the Ideation Mural board here? Thank you.

**Comment by maryjiang-ibm** [comment]
> @maryjiang-ibm Can you add the link to the Ideation Mural board here? Thank you.

This Mural [link](https://app.mural.co/t/dgcdesign5626/m/dgcdesign5626/1622060198460/9ac9b548f3f8c055b38571a48d429f67d6ddaceb?sender=uc3295538086ad1032fc24245) is in the task description.

**Comment by maryjiang-ibm** [comment]
![image](https://user-images.githubusercontent.com/84742894/121252206-bcd90480-c875-11eb-9879-2088d9025bde.png)
Visual exploration 1 in dark and light, with colors up for discussion. Another exploration to come.

**Comment by JennySanchez** [comment]
@maryjiang-ibm Great start with the project logo, and I appreciate you explore both dark and light themes here since we will use it for the presentation. It's always good to make sure the project logo works for both dark and light backgrounds.

You mentioned you would like to get feedback on the color options for now. I think purple works better for representing the transformation and transition.

![Screen Shot 2021-06-09 at 3 49 15 PM](https://user-images.githubusercontent.com/45213839/121427413-4c47eb80-c93a-11eb-9ab5-fe99e274b473.png)


I am looking forward to seeing additional explorations!

**Comment by maryjiang-ibm** [comment]
![image](https://user-images.githubusercontent.com/84742894/121731422-e8026480-cabe-11eb-8586-5c41cd122865.png)
Exploration DEUX: Cartoon à la [Solar Opposites ](https://www.indiewire.com/wp-content/uploads/2019/07/Solar-Opposites.png)(where we found inspiration from their Pupa character). This line style with the geometric shapes is an abstraction of "transformation", with the overall shape resembling a pupa. 

The 2nd (middle) option is the main one. The 3rd (rightmost) is a hail-mary inspired by the eye illustration style in Solar Opposites.

**Comment by maryjiang-ibm** [comment]
![image](https://user-images.githubusercontent.com/84742894/121743199-f9536d00-cace-11eb-872d-d9bb275926e6.png)

**Comment by maryjiang-ibm** [comment]
[pupa logo.ai.zip](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/6677428/pupa.logo.ai.zip)
WIP source file with logo explorations to date.
