### ISSUE TITLE
Project Pupa: Stakeholder Interviews 

### ISSUE THREAD

**Issue by vinushad-ibm** [carbon-design-system/carbon-for-ibm-dotcom-website#1025]
### Objectives
To reach out to project stakeholders to understand the target user and which teams and individuals would benefit the most from the Carbon for IBM.com redesign plan. 

### Tasks

- [x] Set up a call to meet with [Linda](https://ibm.ent.box.com/notes/817271705873?s=9m4o9hhn5xzvg20ejre0pmo5g5zzwf01), Adopter SME and Product owner  

     -  Learn more about the primary end user and understand who the adopter teams are and how they are organized. (Ex. tiers) 

     - Understand the vision of what the website should be from the perspective of the product owner 

    - Learn more about our project objectives 

     - Get recommendations of target users and potential interviewees

- [x] Set up a call to meet with [Jeff](https://ibm.ent.box.com/notes/817641766131), Developer, Development SME and Tech Lead

     -  Understand the user from a developer's perspective 

     - Learn more about how developers use the Carbon for IBM.com website

     -  Understand how the Carbon for IBM.com Dev Team connects and works with adopter teams. 

### Acceptance Criteria

- [x] Get a list of 12 potential users/interviewees from Linda 

- [x] Understand the type of users that would benefit from the Carbon for IBM.com redesign

- [x] Align on next steps and tasks necessary to ensure project success

**Comment by vinushad-ibm** [comment]
User Interviewee list has been completed and can be viewed [here](https://ibm.ent.box.com/notes/817355003103). 
@JennySanchez
