### ISSUE TITLE
Project Pupa:  Design Language Systems Research

### ISSUE THREAD

**Issue by IsiImoisi-ibm** [carbon-design-system/carbon-for-ibm-dotcom-website#1026]
### Objective: 

Conduct design research to find out how other design systems present the information for their adopters.

### Tasks:

Design Language Systems to be researched include:

- [ ] NorthStar- [NorthStar](https://northstar.aws-prototyping.cloud/) 

- [ ] Carbon- [Carbon Design System](https://www.carbondesignsystem.com/)

- [ ] Google- [Material Design](https://material.io/design/introduction)

- [ ] Apple- [Human Interface Guidelines](https://developer.apple.com/design/)

- [ ] Microsoft- [Fluent Design System](https://www.microsoft.com/design/fluent/#/)

### Acceptance criteria

- [ ] Have a better understanding of competitor design system languages 

- [ ] Integrate ideas and IAs on a Collective Document
