### ISSUE TITLE
Project Pupa: Adopter As-is Journey Map

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#1034]
@JennySanchez commented on [Mon Jun 07 2021](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6300)

### Objective:

We will create an Adopter As-is Journey Map to spot pain points and solution opportunities based on interview findings.

### Tasks:

- [ ] Set up the Mural board for the As-is Journey Map creation.
- [ ] Schedule work sessions to work on the maps together as a team based on the findings synthesizing from the interviews. Note: Synthesizing work will be recorded in task issue X.

### Acceptance criteria (The meaning of "Done")

- [ ] Have journey map ready to share with the team.
- [ ] Create task issue for the next step.

**Comment by JennySanchez** [comment]
**[Mural board](https://app.mural.co/t/dgcdesign5626/m/dgcdesign5626/1621965961773/b78fd0e55b02fe50986827856915cacf4f6a9086?sender=chsanche) set up ready in the project space** - some updates will required when we are ready to get started.

![Screen Shot 2021-06-07 at 5 59 50 PM](https://user-images.githubusercontent.com/45213839/121098664-f8af9380-c7bb-11eb-8fce-a1cdf65eac49.png)
