### ISSUE TITLE
Project Pupa: Craft adopter interview scripts

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#1038]
### Objectives
Finalize the interview questions to start scheduling the interviews after Jen Price sends the kick-off email.

### Tasks

- [x] Update the interview questionnaire we have based on the feedback from Jan
- [ ] Update the interview questions we have based on the As-Is journey map creation criteria
- [x] Shared the updated questions with Jan for finalization

### Acceptance Criteria

- [ ] Adopter interview questions (for the designer, developer, and product manager, or stakeholders) are finalized and ready to be used for interviews.

**Comment by JennySanchez** [comment]
✏️ Draft interview script can be viewed [in the BOX folder](https://ibm.box.com/s/311xhrwby03wbkbstjkmj5dshhg48o2m).

**Comment by JennySanchez** [comment]
@vinushad-ibm Once we have the scripts updated, can you make an update by commenting here? Thank you.

**Comment by vinushad-ibm** [comment]
The final interview script draft can be found [here](https://ibm.ent.box.com/notes/820273246361)

**Progress So far:**
- The team brainstormed specific questions we could direct at designers, developers and PMs
- Met with Jenny and prioritized extra questions from most to least important 
- Reorganized interview questions into clear sections and streamlined the flow 

**Next Steps:**
- [ ] Meet with Jan Child to get a content writer's perspective of our script
- [ ] Reorganize the interview script as necessary
- [ ] Finalize interview script

**Comment by vinushad-ibm** [comment]
Interview script will be shared with the Patterns team and will be modified as needed.
