### ISSUE TITLE
Project Pupa: Adopter Interview Beta test

### ISSUE THREAD

**Issue by vinushad-ibm** [carbon-design-system/carbon-for-ibm-dotcom-website#1056]
### Objectives:
To evaluate the the latest [interview script ](https://ibm.ent.box.com/notes/820273246361)that Project Pupa developed for the adopter stakeholder interviews by conducting a beta test with [Daniel Ratzenboeck ](https://w3.ibm.com/bluepages/profile.html?uid=059105618)

### Tasks: 
- [x] Conduct a mock interview 
- [x] Evaluate the flow and timing of our script
- [x] See whether the questions developed reflect our research questions and evoke the intended response from adopters
- [x] Add any follow up questions if necessary
- [x] Clarify any questions that may be ambiguous

Interview is scheduled for Thursday, June 17th @10am EST

**Comment by vinushad-ibm** [comment]
Conducted mock interview with Daniel Ratzenboeck and collected feedback. Will retrospect with the team and revise the script as necessary.
