### ISSUE TITLE
Project Pupa: Process slack messages from #carbon-for-ibm-dotcom

### ISSUE THREAD

**Issue by maryjiang-ibm** [carbon-design-system/carbon-for-ibm-dotcom-website#1068]
### Tasks
- [ ] Categorize messages into categories (question type, component-in-question)
- [ ] Create a chart visualization based on the organized message data

### Acceptance criteria
- [ ] Airtable or exported image of visualizations/charts

**Comment by maryjiang-ibm** [comment]
All relevant messages are now categorized on the [Airtable](https://airtable.com/invite/l?inviteId=invgg9aDo3DGaluXn&inviteToken=639632fa03f84e019952f5747d7df19ab13444de8834636cdebb5204e488603b&utm_source=email). May need to reorganize the larger categories into smaller categories.
