### ISSUE TITLE
IBM.com Style Model Grid Guideline (part 1)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#1075]
> As an IBM.com Library adopter

> I need a guideline to follow and effectively use the IBM.com style model grid,

> so that I can create a consistent experience across the IBM.com.

---

#### ✏️ Additional information

- Website content publishing process detail can be viewed [here](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj).

#### Tasks
- [ ] Research and collect references
- [ ] Craft content and finalize the guideline content
- [ ] Design and finalize the guideline page design
- [ ] Create and publish the guideline on the website

#### Acceptance criteria
- [ ] IBM.com Style Model Grid Guideline published on the website.

**Comment by shixiedesign** [comment]
Updated style model proposal: ![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/6a301642-a0b5-45ad-a873-11d94e538d18)
