### ISSUE TITLE
Website v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1568]
## Epic to track the v2 website issues

```[tasklist]
### First steps
- [ ] Audit
- [ ] Remove or hide pages
- [ ] Cut branch
```

```[tasklist]
### About Carbon for IBM.com
- [ ] About us
- [ ] Adopting the system
```

```[tasklist]
### Designing
- [ ] Get started
- [ ] Figma kit
```

```[tasklist]
### Developing
- [ ] Get started
- [ ] Frameworks
- [ ] Other packages
- [ ] Building for IBM.com
- [ ] Carbon CDN style helpers
- [ ] Web Components tutorial
```

```[tasklist]
### Contributing
- [ ] Overview
- [ ] Documentation
- [ ] Components
- [ ] Patterns
```

```[tasklist]
### Guidelines
- [ ] Content
- [ ] Expressive styling
- [ ] Layout
- [ ] Right to left languages
- [ ] Spacing
- [ ] Style models
```

```[tasklist]
### Components
- [ ] Remove pages
- [ ] Overview
- [ ] Back to top
- [ ] Callout quote
- [ ] Callout with media
- [ ] Cards
- [ ] Card group
- [ ] Card section
- [ ] Card section carousel
- [ ] Carousel
- [ ] Content block
- [ ] Content block cards
- [ ] Content block horizontal
- [ ] Content group
- [ ] Content group banner
- [ ] Content group cards
- [ ] Content group pictograms
- [ ] Content group simple
- [ ] Content item
- [ ] Content item horizontal
- [ ] Content section
- [ ] CTA
- [ ] CTA block & section
- [ ] Dotcom shell
- [ ] Expressive modal
- [ ] Feature section
- [ ] Filter panel
- [ ] Footer
- [ ] Horizontal rule
- [ ] Images
- [ ] Language selector
- [ ] Layout
- [ ] Lead space
- [ ] Lead space block
- [ ] Lead space search
- [ ] Leaving IBM modal
- [ ] Lightbox media viewer
- [ ] Link list
- [ ] Link list section
- [ ] Link with icon
- [ ] Locale modal
- [ ] Logo grid
- [ ] Masthead
- [ ] Pictogram item
- [ ] Quote
- [ ] Table of contents
- [ ] Tabs extended
- [ ] Tags
- [ ] Universal banner
- [ ] Video
```

```[tasklist]
### Patterns
- [ ] Overview
- [ ] Call to action
- [ ] Cards
- [ ] In-page navigation
- [ ] Lead space
```

```[tasklist]
### Resources
- [ ] Resources
```
```[tasklist]
### Help
- [ ] Overview
- [ ] FAQ
```
