### ISSUE TITLE
[Website] Callout with media

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1569]
Update Callout with media component page with updates for v2

### Tasks
- [ ] Grid updates?
- [ ] Color options
- [ ] Image should switch to default color (not inverse)
- [ ] Check content guidance is accurate
- [ ] Resources: Remove React storybook, Sketch and func specs(?) links
- [ ] Resources: Add Figma?

### Acceptance criteria

- [ ] Check if a page design exists to leverage new [images](https://ibm.ent.box.com/folder/151141324220)
- [ ] Utilize the [Component page template](https://ibm.ent.box.com/folder/147223579360)
- [ ] If a page is missing chunks of the template, make a new issue to address the missing pieces
- [ ] Utilize the Image production kit to create new images
- [ ] Resources links are cleaned up
- [ ] Page must be reviewed by a team member
