### ISSUE TITLE
Add stakeholder and team member contact list to our wiki and website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#287]
> As an IBM.com library adopter,

> I need a way to know who I should reach out to for assistant around a particular service on IBM.com

> So that I can reach out to the correct contact to assist me.

#### Additional information
When thinking about the goal we have for our IBM.com adopters, I spot a need to connect the design leads from each of the IBM.com teams. My thought is to add a link on our Get Started/Overview Page and a card on Help/Overview Page then linked them to the contact list on the team Git wiki.

#### Tasks
- [x] Collect adopter lead information
- [ ] Create list on Wiki
- [ ] Add links on the website

#### Acceptance criteria
- [ ] List is published on the live website.

**Comment by JennySanchez** [comment]
@wonilsuhibm Let me know what do you think?

**Comment by JennySanchez** [comment]
@jacobottesen-dgc This list should be the same one as the one you are working on for the Adopter Kit. When the list is done, let's create a link on the website for linking so adopters can find the information.

**Comment by jacobottesen-dgc** [comment]
Based on a conversation with Wonil, we will not have the contact list in the adopter kit but we will have a short list with Linda, Jeff, and Wonil. The list can be found in: https://ibm.box.com/s/q3u4v28z3l1fph1vrovnco59dq0k85l2

**Comment by wonilsuhibm** [comment]
@jacobottesen-dgc let's hold off on this. let's use the `#ibm-digital-design` channel as much as possible before surfacing any direct contact.

**Comment by jacobottesen-dgc** [comment]
@RobertaJHahn It looks like we are going to hold off on those update to the cupcake site. Could you take this off Sprint 15 and move it to backlog?

**Comment by RobertaJHahn** [comment]
Moving to backlog

**Comment by JennySanchez** [comment]
Let's close this task, we decided to not have the list of the stakeholder listed on the website.
