### ISSUE TITLE
Update leadspace content to align with dev refactor

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/carbon-for-ibm-dotcom-website#347]
Due to the dev refactoring, the `lead space` content and documentation needs updating. Dev decided to combine all lead space types under one pattern: lead space with different styles. Currently, we don't have that information or language on the website.

## Additional information
We (Wonil, Olivia, Lara) agreed on the following names for lead space styles:

1. Lead space, left-aligned, informational
2. Lead space, left-aligned, display
3. Lead space, centered

Current content: https://ibm-dotcom-library.mybluemix.net/patterns/leadspace

## Tasks
- [ ] Review dev set up to understand the changes
- [ ] Review current lead space content on the website and identify discrepancies
- [ ] Make copy edits to content
- [ ] Review and update images

**Comment by JennySanchez** [comment]
**Note:** The "Pattern in Use" section image redesign can be viewed via #376 . The images are not finalized and will be implemented and designed into the design along with the content update.

**Comment by JennySanchez** [comment]
Hi @larahanlon2  We no longer use the term "Ontology", so we might need to update the task detail. 

For all sub-tasks created for website content update, let's tag it under the EPIC 496.
Let me know when you think we can work on the update detail together and get it prioritized.

**Comment by JennySanchez** [comment]
@larahanlon2 Is this task still relevant?

**Comment by JennySanchez** [comment]
@wonilsuhibm @oliviaflory Can you both take a look at this task issue and let me know if the task still relevant? Thank you.

**Comment by JennySanchez** [comment]
This task no longer relevant.
