### ISSUE TITLE
Create and publish - Spacing Guideline

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#357]
> As an IBM.com Library adopter

> I need a guideline to follow and effectively set the correct spacing for the IBM.com experience,

> so that I can create a consistent experience across the IBM.com.

---

#### ✏️ Additional information

- Website content publishing process detail can be viewed [here](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj).

- Reference (dot-com-theme--spacing--1.0.1) for spacing in different breakpoints can be viewed [here](https://ibm.box.com/s/z790x8f9kvluwnm09ctrxdyh7p2zx8ku).

#### Tasks
- [ ] Research and collect references
- [ ] Craft content and finalize the guideline content
- [ ] Design and finalize the guideline page design
- [ ] Create and publish the guideline on the website

#### Acceptance criteria
- [ ] Line length guideline published on the website.

**Comment by JennySanchez** [comment]
@wonilsuhibm @RobertaJHahn FYI on this EPIC existed.

**Comment by JennySanchez** [comment]
This task needs to be prioritized.

**Comment by JennySanchez** [comment]
Task #641 is created for the actual work and all publishing task will be collected under the Epic #646.
This Epic can be closed, @RobertaJHahn.
