### ISSUE TITLE
(Cupcake Website) Tile view implementation for the Components overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#545]
#### Note
The finalized wireframe images for the tile view can be found via #544 .

### Tasks

- [ ] Go over the task detail and kick off with Jenny.
- [ ] Implement the tile set up with the wireframe images Jacob created to the Components overview page with code.
- [ ] Share the preview link with Jenny for QA.
- [ ] Merge PR for the tile view to go live on the Cupcake Website.

### Acceptance criteria
- [ ] All Components and Layout Patterns are presented in the Tile view live on the cupcake website.

**Comment by JennySanchez** [comment]
This task is completed in Sprint 20-20 and the gallery can be viewed live on the website [here](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/gallery).
