### ISSUE TITLE
Create the MVP content template for the Core Components section

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#557]
Based on the discussion I have with Wonil, Olvia, and Lara. We spot the need to present token used in the component to the adopters rather than the Spec files. 

#### Task:

- [ ] Update the MVP content template based on the discussion.
- [ ] Share the updated template with Wonil, Olivia, and Lara for feedback.
- [ ] Update the template based on the feedback received and as needed.
- [ ] Finalize the template.
- [ ] Share the template with the DDS team and update the link in the Components website pages publishing git template.

#### Acceptance criteria

- [ ] Have the MVP content template for the Component section ready to be used for publishing.

**Comment by JennySanchez** [comment]
Based on the conversation I had with @oliviaflory  and @wonilsuhibm, this task is for the Core Components which is not the focus for the publishing we are focusing on. We will be focusing on IBM.com Library components (see agreed priority below) for now and we will circle back to this task when it's appropriate.

![Screen Shot 2020-08-03 at 11 40 12 AM](https://user-images.githubusercontent.com/45213839/89205966-2e716380-d57e-11ea-9617-1fd2b1a9c073.png)

**Comment by JennySanchez** [comment]
This task is completed and will be closed.
