### ISSUE TITLE
Create and publish new Patterns content on the website

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/carbon-for-ibm-dotcom-website#615]
#### Objective

We need to update the Cupcake website to reflect the patterns organization work outcome, so adopters can find what they need on the website properly.

#### Tasks

- [ ] Lara to create new Patterns overview page content
- [ ] Lara to create new Patterns guidelines for cards, lead space, in-page navigation
- [ ] Jenny reviews pages
- [ ] Wonile reviews and approves pages
- [ ] Publish pages to the website
- [ ] Update website IA

**NOTE:** 

- This is follow on work from this IA epic: https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/497

### Acceptance criteria

- [ ] The website IA is updated and live on the website.
- [ ] The patterns overview page content is updated and live on the website.
- [ ] The 3 prioritized patterns pages (cards, lead space and in-page nav) are published and available to adopters.

**Comment by JennySanchez** [comment]
@RobertaJHahn We completed the task goal and this Epic can be closed.
