### ISSUE TITLE
01 Content Publishing - Guidelines (Type paring and spacing)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#640]
#### User Story

> As an IBM.com Library components adopter, 

> I need a way to learn more about the IBM.com Library,

> so that I can learn the detail through the guidelines and adopter IBM.com Library to my day to day work properly. 

#### Additional information

**The MVP version content can be found on IBM.com Library wiki - [Type sizes and spacing](https://github.com/carbon-design-system/ibm-dotcom-library-website/wiki/Type-sizes-and-spacing) and the [Component hierarchy & spacing page](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Component-hierarchy-&-spacing#content-group)**

- Work on the content by following the [publishing process](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj) as much as possible and as needed.
- Create the website design with the Sketch App as needed and the Sketch publishing template can be found on the [BOX folder](https://ibm.box.com/s/ma72t84m75fvd3qqkyz8cm6gfx9b7vou). Once complete, save the revised Sketch file in the Guideline folder / sub-folder [here](https://ibm.box.com/s/40lbqd2bfxwm1qv8k6dy8qwyq48qd6xg).
- Once the content is reviewed (with stakholders or SME of the topic) and finalized. 
- Copy the content from the Sketch file into the .mdx file for the markdown publishing process to start.
- Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
- When ready to deploy, include Jenny as a PR Reviewer and Approver.
- Jenny will review and merge the PR

#### Acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done (if needed)
- [x] Page design is done (if needed)
- [x] Publishing with markdowns is done.
- [x] Content is finalized
- [x] QA'd by Jenny
- [x] Web page is published

**Comment by JennySanchez** [comment]
This task is still relevant.

**Comment by JennySanchez** [comment]
This task is relevant and in prioritization.

**Comment by JennySanchez** [comment]
**Note:** The type pairing and spacing go hand-in-hand. Let's see if we can craft the guideline with both of them on the same website page.

**Comment by JennySanchez** [comment]
**Task update:** Worked on the content structure and images based on the designer's feedback.

## Page title: Type pairing and spacing

Intro copy
Anchor link (if needed, TBD)

**Content section**

- Image (Expressive heading 02 and body long 02)
- Token detail
- Spacing table (a.k.a Margin table)

**Content block**

- Image (Expressive heading 05 and heading03)
- Token detail
- Spacing table (a.k.a Margin table)

**Content group**

- Image (Expressive heading 04 and body long 02)
- Token detail
- Layout spacing (a.k.a Margin table)

**Content item**

- Image (Expressive heading 02 and body long 02)
- Token detail
- Spacing table (a.k.a Margin table)

**Comment by JennySanchez** [comment]
Content update completed and shared with designers via Slack for feedback.

![Screenshot_2021-05-18 Type pairing and spacing.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/d3040ef5-186b-4cd9-a180-b51b7adf3078)

**Comment by JennySanchez** [comment]
Task completed. All image work files can be found in the [BOX folder.](https://ibm.box.com/s/p3ptwn7ffi15c6xyg4ia1njb5gxw1xtj)
