### ISSUE TITLE
02 Content Publishing - Guidelines (Spacing guideline)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#641]
#### User Story

> As an IBM.com Library components adopter, 

> I need a way to learn more about the IBM.com Library,

> so that I can learn the detail through the guidelines and adopter IBM.com Library to my day to day work properly. 

#### Additional information

- Work on the content by following the [publishing process](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj) as much as possible and as needed.
- Create the website design with the Sketch App as needed and the Sketch publishing template can be found on the [BOX folder](https://ibm.box.com/s/ma72t84m75fvd3qqkyz8cm6gfx9b7vou). Once complete, save the revised Sketch file in the Guideline folder / sub-folder [here](https://ibm.box.com/s/40lbqd2bfxwm1qv8k6dy8qwyq48qd6xg).
- Once the content is reviewed (with stakholders or SME of the topic) and finalized. 
- Copy the content from the Sketch file into the .mdx file for the markdown publishing process to start.
- Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
- When ready to deploy, include Jenny as a PR Reviewer and Approver.
- Jenny will review and merge the PR

#### Acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done (if needed)
- [x] Page design is done (if needed)
- [x] Publishing with markdowns is done.
- [x] Share markdown preview with designers
- [x] Finalize markdown
- [x] PR final reviewed by Jenny

#### Acceptance criteria
- [ ] ~Web page is published~

**Comment by JennySanchez** [comment]
@wonilsuhibm You mentioned the MVP version content can be found on IBM.com Library wiki, you mean [this document](https://github.com/carbon-design-system/ibm-dotcom-library-website/wiki/Type-sizes-and-spacing)?

**Comment by JennySanchez** [comment]
This task is still relevant and is part of the Guideline publishing Epic.

**Comment by JennySanchez** [comment]
This task is still relevant.

**Comment by JennySanchez** [comment]
@RobertaJHahn This is the task I will be working on with Tom Stribling on the Reboot Team for Sprint 20-03.

**Comment by JennySanchez** [comment]
@wonilsuhibm @RobertaJHahn After talking to Tom, he only have today and next Monday to complete a content crafting task. He will be working on the Content Guideline instead of this one. Let's have this task back to the backlog and re-prioritize.

**Comment by JennySanchez** [comment]
**Task status:** Draft content shared with designers today. The PR and preview link can be found in [PR 1012](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1012).

**Next step:** Finalize the content based on the feedback from designers.

**Comment by JennySanchez** [comment]
**Task status:** Content updated based on the feedback from designers.

**Comment by JennySanchez** [comment]
There's a page title challenge between the Spacing guideline and Type pairing and spacing guidelines when doing the final review. Jan and I think we need to take a look at the IA for the website as a whole. For now, the PR will not be merged, and we will meet next Monday to define the next step.

- The content is done, and in PR, this task issue will be moved to the Done column. 
- The page will be share in the sprint demo.
- The page will be merged, or an additional task issue will be created based on my discussion with Jan on Monday.
