### ISSUE TITLE
Content Publishing - Guidelines (Dev framwork guidelines)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#642]
#### User Story

> As an IBM.com Library components adopter, 

> I need a way to learn more about the IBM.com Library,

> so that I can learn the detail through the guidelines and adopter IBM.com Library to my day to day work properly. 

#### Additional information

- Work on the content by following the [publishing process](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj) as much as possible and as needed.
- Create the website design with the Sketch App as needed and the Sketch publishing template can be found on the [BOX folder](https://ibm.box.com/s/ma72t84m75fvd3qqkyz8cm6gfx9b7vou). Once complete, save the revised Sketch file in the Guideline folder / sub-folder [here](https://ibm.box.com/s/40lbqd2bfxwm1qv8k6dy8qwyq48qd6xg).
- Once the content is reviewed (with stakholders or SME of the topic) and finalized. 
- Copy the content from the Sketch file into the .mdx file for the markdown publishing process to start.
- Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
- When ready to deploy, include Jenny as a PR Reviewer and Approver.
- Jenny will review and merge the PR

#### Acceptance criteria
- [ ] Content crafting is done.
- [ ] Asset image creation is done (if needed)
- [ ] Page design is done (if needed)
- [ ] Publishing with markdowns is done.
- [ ] QA'd by Jenny
- [ ] Web page preview is approved by Linda, Jeff, and Wonil
- [ ] Web page is published

**Comment by JennySanchez** [comment]
@jeffchew Please let know if this content crafting task should be assigned to you or anyone on the dev team who can contribute to the framework content crafting.

**Comment by jeffchew** [comment]
Can you give an overview of what this issue is for exactly? I'm not quite understanding from the description.

**Comment by JennySanchez** [comment]
Hi @jeffchew 
This task is to craft content for the guidance around development frameworks for IBM.com Library adopters, such as React and Web Components. Some of the information might be covered in the [Coding Page](https://www.ibm.com/standards/web/ibm-dotcom-library/get-started/coding). Please also see the [Carbon Framework page](https://www.carbondesignsystem.com/developing/frameworks/react) for reference.

**Comment by JennySanchez** [comment]
This task is still relevant.

**Comment by JennySanchez** [comment]
This task is relevant and in prioritization.

**Comment by JennySanchez** [comment]
**Task status:** Page structure set up with placeholder text. The PR and preview link can be found in [PR 1014](https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1014/index.html).

**Next step:** I shared the structure with Linda and Jeff for input and need to collaborate with a Dev to add additional content.

**Comment by JennySanchez** [comment]
@RobertaJHahn Based on the conversation with @jeff. We will bring this task to next week's Engineering Epic and Story refinement call for assigning a developer to work on the additional content based on the structure I set up. Jeff mentioned research work would be involved, and we might need to adjust story points.

**Comment by JennySanchez** [comment]
@RobertaJHahn The task issue will be presented in the Engineering Epic, and Story refinement call the following Monday. We will move this task issue to Sprint 21-12.
