### ISSUE TITLE
Content Publishing - Guidelines (11 Content guideline)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#643]
#### User Story

> As an IBM.com Library components adopter, 

> I need a way to learn more about the IBM.com Library,

> so that I can learn the detail through the guidelines and adopter IBM.com Library to my day to day work properly. 

#### Additional information

- Work on the content by following the [publishing process](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj) as much as possible and as needed.
- Create the website design with the Sketch App as needed and the Sketch publishing template can be found on the [BOX folder](https://ibm.box.com/s/ma72t84m75fvd3qqkyz8cm6gfx9b7vou). Once complete, save the revised Sketch file in the Guideline folder / sub-folder [here](https://ibm.box.com/s/40lbqd2bfxwm1qv8k6dy8qwyq48qd6xg).
- Once the content is reviewed (with stakholders or SME of the topic) and finalized. 
- Copy the content from the Sketch file into the .mdx file for the markdown publishing process to start.
- Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
- When ready to deploy, include Jenny as a PR Reviewer and Approver.
- Jenny will review and merge the PR

#### Acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done (if needed)
- [x] Page design is done (if needed)
- [x] Publishing with markdowns is done.
- [x] QA'd by Jenny
- [x] Web page preview is approved by Linda, Jeff, and Wonil
- [x] Web page is published

**Comment by JennySanchez** [comment]
This task is still relevant and is part of the Guideline publishing Epic.

**Comment by JennySanchez** [comment]
**NOTE:** We need to add character count best practice for card as part of the content.


![image.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/7acf617f-0916-48eb-88ac-7fd4cd603b2a)

**[Conversation on reboot-dds-collaboration](https://ibm-studios.slack.com/archives/GVAG3EPDG/p1606239268106700)**


![Screen Shot 2020-11-24 at 12.10.14 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/20269f0d-cee5-4b32-8598-7a96c88bef62)

**Comment by JennySanchez** [comment]
Resource:
**Carbon website content guideline:** https://www.carbondesignsystem.com/guidelines/content/overview/

**Comment by JennySanchez** [comment]
@RobertaJHahn This is the task I will be working on with Tom Stribling on the Reboot Team for Sprint 20-03.

**Comment by JennySanchez** [comment]
@wonilsuhibm @RobertaJHahn After talking to Tom, he only have today and next Monday to complete a content crafting task. 

@wonilsuhibm Tom asked for content structure, and I created this [BOX document](https://ibm.box.com/s/x1qa0md6hccygdf8tjpbyulywqfo0fww) with sections to help him get started. For alignment purposes, can you take a look and let me know if it's good to share with him?

**Comment by JennySanchez** [comment]
I followed up with Tom, and he will work on the content based on the structure we set up for him.![Screen Shot 2021-02-10 at 12.07.15 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/e663021a-ca3c-4c3d-ac40-c1e8a8969733)

**Comment by JennySanchez** [comment]
Initial Draft from Tom:
[https://app.zenhub.com/files/202376156/d580572e-d2f5-43f5-9980-e255fcac90c2/download](https://app.zenhub.com/files/202376156/d580572e-d2f5-43f5-9980-e255fcac90c2/download)

**Comment by JennySanchez** [comment]
Below is the latest Content Guideline website page content from Tom. 
The next step is to get feedback from the DDS designers and finalized the MVP Content Guideline. 


[https://app.zenhub.com/files/202376156/3014c063-1124-4680-81bb-e00e33031166/download](https://app.zenhub.com/files/202376156/3014c063-1124-4680-81bb-e00e33031166/download)

**Comment by JennySanchez** [comment]
**Task update:** Bring the content into markdowns, and once it's done, I will share the preview link with designers to get feedback.

**Comment by JennySanchez** [comment]
Markdown completed and PR detail can be viewed [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/868).

**Comment by JennySanchez** [comment]
Website page is live on the website and can be viewed [here](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/guidelines/content).
