### ISSUE TITLE
Content crafting and publishing: Contribution/Overview Page (general contribution and process detail)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#657]
#### User Story

> As an IBM.com Library adopter, 

> I need guidance on how to contribute back to the IBM.com Library,

> so that I can support the growth of the IBM.com Library. 

#### Location of the content presented on the website:

Depends on the new content, we might make updates on the current Contribution overview page, or add a page under the Contribution section.

#### Additional information

- Work on the content by following the [publishing process](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj) as much as possible and as needed.
- Craft content based on the idealization outcome of the I[deation: Contribution Detail page](https://github.com/carbon-design-system/digital-design-ideation/issues/141) task on the ideation board.
- Create the website design with the Sketch App as needed and the Sketch publishing template can be found on the [BOX folder](https://ibm.box.com/s/ma72t84m75fvd3qqkyz8cm6gfx9b7vou). Once complete, save the revised Sketch file in the Guideline folder / sub-folder [here](https://ibm.box.com/s/40lbqd2bfxwm1qv8k6dy8qwyq48qd6xg).
- Once the content is reviewed (with stakeholders or SME of the topic) and finalized. 
- Copy the content from the Sketch file into the .mdx file for the markdown publishing process to start.
- Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
- When ready to deploy, include Jenny as a PR Reviewer and Approver.
- Jenny will review and merge the PR

#### Acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done (if needed)
- [x] Page design is done (if needed)
- [x] Publishing with markdowns is done.
- [x] QA'd by Jenny
- [x] Web page preview is approved by Linda, Jeff, and Wonil
- [x] Web page is published

**Comment by JennySanchez** [comment]
@ljcarot This is the task issue for the Contrbution Model content crafting. I know you started on the "Contribution Model" content work. Please let me know how I can assist you in getting the content on the website before the summit.

**Comment by JennySanchez** [comment]
@RobertaJHahn As discussed, moving this task to Sprint 20-21.

**Comment by JennySanchez** [comment]
**Contribution License Agreement (CLA)** template from Jeff.
https://ibm.box.com/s/wil1i5bxykry18kuvl1gofsk30l67nwd

**Comment by jeffchew** [comment]
@JennySanchez should we convert this to a PDF before publishing this?  I'm also wondering if there are any legal reasons to not have this readily available on a public website.

**Comment by JennySanchez** [comment]
@jeffchew Good point, I am not sure if there are any legal reasons but we should look into it. Also, If we are going to send it to external contributor after they submit the contribution PR, will this still be a possible concern?

**Comment by JennySanchez** [comment]
**Task update:** Initial content was reviewed with Linda and Jeff today. Round one content in markdowns and PR can be viewed [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/695).
