### ISSUE TITLE
Components Overview Page update: based on Adopter feedback and audit findings

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#677]
#### Objective

The [Components Overview Page](https://www.ibm.com/standards/web/ibm-dotcom-library/components/overview) IA, overview table list update, and the implementation of the Gallery View were done in Sprint 20-19.
We need to share the content with adopters and get feedback on how we can make it better.

This task issue is created to recording the feedbacks and define the next step action items.

#### Task

- [ ] Share the page with adopters and get feedback
- [ ] Synthesize feedback and group them into categories
- [ ] Share findings with the DDS team
- [ ] Align on the action items for future improvement

#### Acceptance criteria

- [ ] Ready to create task issues for the action items

**Comment by JennySanchez** [comment]
Per @jacobottesen-dgc : The Layout Components thumbnails images seem to be smaller compared to the UI Components images on the Gallery view.

**Comment by JennySanchez** [comment]
We need to work on this in Q4.

**Comment by JennySanchez** [comment]
This task is covered by two other tasks we did in Sprint 25 and we are ok to let the Stale bot close it.
