### ISSUE TITLE
Training: How to solve PR conflicts 

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#678]
> as an IBM.com Library team member,

> I need a way to resolve conflict when I create PRs

> So that I can resolve the conflict and move forward without dev assistant.

#### Task

- [x] Reach out to @kennylam and set a time and date for the lesson
- [x] Share the lesson info with the team members
- [x] Set up the course invite on Calendar

#### Acceptance criteria
- [x] Team members are confident and know how to work around the conflicts.

#### Note:
This will be on-going learning for everyone on the team, especially designers. The course will only cover basic conflict solving skills.

**Comment by JennySanchez** [comment]
@kennylam Let's work on this in Sprint 20-22. I will set something up for us. Thank you.

**Comment by JennySanchez** [comment]
**Task update:** Learning session with Kenny set up for 11/02 (Monday).

**Comment by JennySanchez** [comment]
Session done and the recording can be viewed [here](https://ibm.box.com/s/8zvi0s7cqocq5vbpzfd753i9v2m6fyrl).
