### ISSUE TITLE
Update the Masthead component page - Target sprint 20-24

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#731]
**User story**
As a DDS designer I need to update the Masthead component page to reflect the updates made to the Masthead L0 and L1.

The current masthead component documentation is slightly different from the MVP content template. I believe this unique content order and sections were created to address the complexity of the masthead.

**Tasks** 
- [x] Review the current content sections and determine if they need to be updated

- [x] Update the content to reflect all L1 changes
- [x] Update the images of the L1 to reflect all changes
- [x] Update behavior section to include overflow feature 
- [x] Share with Jenny and Wonil for approval

**Acceptance criteria**
- [ ] Content drafted and approved by Wonil and Jenny
- [ ] Content and design updated with markdowns.

**Comment by oliviaflory** [comment]
The current masthead component documentation is slightly different from the MVP content template Jenny created. I believe this unique content order and sections were created to address the complexity of the masthead.

### Current sections
**Masthead Level 0**
- image of L0

**Masthead** Level 1
- image of L1

**Development documentation**
- link to React and Web component storybook

**Variations**
Default L0
- images of all variations (platform name only, platform + navigation links, etc.

Default L1
- images of all variations

**Anatomy**
- image detailing all pieces of the masthead L0 & L1

_Sections describing pieces:_ 

- Titles
- Nav link labels
- Navigation
- L1 eyebrow

**Behavior**
- images showing how the masthead looks at different breakpoints

----
### Proposed update
*I'd like to follow the template Jenny created, and add an Anatomy and Behavior section to address the complexity of the masthead*

**Default**
- L0 default

**Variations**
- Search open by default
- with Platform
- with L1

**Anatomy**
Detail out the pieces that comprise the masthead

L0
- Logo
- Platform (Ecosystem name)
- Links
- Search
- Profile

L1 pieces
- Logo
- Platform (Ecosystem name)
- Links
- Search
- Profile

**Behavior**
- breakpoints
- overflow

**Design & functional specs**
*Note: We need to consolidate the L0 and L1 designs folders into one "Masthead" component folder like Storybook; or have two separate links for L0 and L1*

**Dev documentation**

**Feedback**

---

@JennySanchez @wonilsuhibm @ljcarot please let me know what you think of the above proposal

**Comment by JennySanchez** [comment]
@oliviaflory I like the proposed update structure because it creates a cohesive browsing experience for the adopters. Lara and I talked about update the content structure for Masthead, Footer, and Lead space when we work on the updates in the past, so you are on the right track here.

**Comment by ljcarot** [comment]
@oliviaflory i like the anatomy and behavior breakdown too.  I agree we should have one masthead folder too

**Comment by wonilsuhibm** [comment]
This makes sense. Thank you @oliviaflory

**Comment by JennySanchez** [comment]
@oliviaflory @wonilsuhibm Based on the conversation we had in the DDS design review & crit session, below is the updated content structure for the Masthead. Please let me know if I missed anything.

### Masthead — L0
**Default
Variation**
     - Seach open by default
**Anatomy
Behavior**

### Masthead — L1
**Default
Anatomy
Behavior**

**Comment by JennySanchez** [comment]
@oliviaflory **FYI:** Comments were added to the [PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/746) after taking a look at the draft content as requested.

**Comment by wonilsuhibm** [comment]
@oliviaflory Thank you!

### Intro
"There are two different variations of the masthead, which one is used depends on the page type. Masthead – L0 contains the default navigation for all of IBM.com and is most commonly used on the IBM.com homepage. Masthead – L1 is utilized for almost all other pages on IBM.com."

Does the part about there being two variations sound like L0 and L1 are the two variations? Maybe changing the names from "Masthead - L0" and "Masthead - L1" to "Masthead - with L0" and "Masthead - with L1" may help.

### Names

Sometimes the two variations are called "Masthead - (with) L1", other times "Masthead Level 1". Should we use the same naming?

### IBM Logo under [Anatomy](https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/746/components/masthead#anatomy)

Should we be more assertive here by saying things like "do not change the logo without talking to us"?

### [Behavior](https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/746/components/masthead#behavior)

Should we touch upon the centering behavior—when the browser is wider than the max break-point, how the layout maxes at 1584 and margins are added on both sides? A simple visual would be nice too.

### Overflow caroulse

When we have the time, let's add an animated GIF to showcase how this works/

### Masthead with L1 behavior / overflow carousel

Is the visual that shows the logo, the platform name, and nav items on a singlebar correct? Shouldn't it be the double decker design?

**Comment by oliviaflory** [comment]
I can't find a real example where the L1 would actually trigger the overflow, the current content model set up by reboot seems to be less than 800px wide, so I might comment out the L1 carousel part for now?
