### ISSUE TITLE
⭐️ Template // Website content updates: (Name of the category/ Name of the website page)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#738]
## Objective
Provide Carbon for IBM.com adopters the most up-to-date best practice, tool, and resource as soon as it's available.

## Content update summary
👉 `Depends on the update, please add adopter needs or task summary here.`

## Tasks
👉 `Depends on the update, please add necessary step details here for reference.`

## General publishing process
Depends on the content for updates, please make sure you read the content crafting process by viewing the **[2020 website content publishing process box document](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj)** before you dive into the task.

## Updating website page content
- Update content crafting starts as soon as publishing agreements are accepted by the DDS leadership team.
- Content updates to the live website can be done via code or markdowns. If you need guidance on how to work with markdowns, please see the step by step instruction in the [Editing and publishing in Github Box document](https://ibm.box.com/s/as8fo8gcecvizngxgq2dpuk4po2alq7t).

## File naming and storage
- Name the Sketch file with the following convention: Name of the category + components/pattern/guideline + version. ex: Components-Feature card block v1.0, Guidelines-Expressive theme v1.0, Help-Overview v1.0 and etc.
- Please save all content publishing work files (box, markdowns link, or Sketch file) in the proper sub-folder under the[ ✍️ Content + Design folder](https://ibm.box.com/s/tty3jhshkt6l18jkn2v5ac2uznyjexns).

## Publishing acceptance criteria
Depends on the update, what listed below is the standard criteria, please add the necessary criteria below.

- [ ] Update content crafting is done.
- [ ] Asset image creation is done (as needed).
- [ ] Page design is done (as needed).
- [ ] Publishing with markdowns is done.
- [ ] QA'd by Jenny.
- [ ] Web page preview is approved by Linda, Jeff, and Wonil.
- [ ] PR merged by Jenny.
- [ ] Web page is published and live on the website.

---

## Additional steps before you get started
👉 `Depends on the scope of the content update, the story points for the task might vary. Please make sure you update the story point. If you know the Milestone, Epic, and Releases based on the DDS leadership priority agreement, please feel free to update them as well. `

**Comment by JennySanchez** [comment]
@RobertaJHahn We still need this template, correct?

**Comment by RobertaJHahn** [comment]
@JennySanchez Not sure why stalebot is "finding' the website templates.  Stalebot is supposed to ignore issues with the `icebox` label in the icebox pipeline.

**Comment by RobertaJHahn** [comment]
No longer needed.  Closing
