### ISSUE TITLE
Design the Checklist for IBM.com Web Standard website - Target Dec 18

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#748]
@JennySanchez commented on [Wed Nov 18 2020](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4517)

> As an IBM.com Web Standard adopter,

> I need a way to view all the requirements and learn all the standards I need to meet

> So that I can create an user centered experience for IBM.com visitors.

#### Note
Design ideation and conversation detail can be viewed via #150 on the ideation board.
https://github.com/carbon-design-system/digital-design-ideation/issues/150

#### Tasks
- [x] Work on the designs based on the ideation outcome
- [x] Share design with Linda, Jo, and Wonil to get feedback
- [x] Revised design based on the feedback
- [x] Share design with DDS team member for feedback
- [x] Finalize the design

**Comment by JennySanchez** [comment]
**Task update:**
Met with Linda and Wonil today to review initial designs and decided on the direction for revision.

- We will move forward with the no left navigation option.
- We will organize content into categories, preferable three categories.
- We will focus on using the card format for the listing.
- We will utilize the pictogram at the category level.
- We will explore ideas around filtering the list by adopter roles (developer, designers, etc) if possible.

**Next Steps:** 

- Share the recommended design direction from today's meeting with Jo (Jo scheduled a meeting for tomorrow 3:30 to 4:00 pm CT)
- Get a list of the standards and guidelines from Linda or Jo for the design revision.
- Organize the list content into categories.
- Work on the design revision based on the initial design review outcome.

**Comment by JennySanchez** [comment]
@ljcarot Below are the v1 design to share and go over with Jo and the guidelines section organization are listed as discussed via Slack.

![Idea A.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/88282e89-d50e-4f3b-9316-17aca4a8a09a)![Idea B.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/1cbf47e9-002c-4040-a3c8-3f121c95e7bc)

**Comment by ljcarot** [comment]
So we should say now we are "over 20 million" @JennySanchez

**Comment by JennySanchez** [comment]
Thank you in advance for taking a look at the copy for updates, @ljcarot  (a.k.a. Content Strategist)!

**Lead space copy:**
Keep IBM.com in good standing, from a compliance, security and auditability standpoint.

**Checklist intro copy:**
With over 40 million pages on IBM.com, the checklist below is a list of standards that transcend the design system in use both necessary for consistency but also required for efficiency.

**Inquiries section copy:**
As usage changes and testing reveals new insights, standards are subject to change. For inquiries about changing a standard based on research, testing and/or new policy, please open an issue in our Github repository.

**Blue message bar copy:**
Please be aware that v18/v19a design systems are targeted to be sunset at the end of 2021.

**Comment by ljcarot** [comment]
**Lead space copy:**
IBM web standards must be followed to ensure brand, technical and legal compliance.

**Checklist intro copy:**
With over 20 million pages on IBM's domain, governance and adherence to standards is paramount.  The checklist herein provides access to more detailed mandatory standards for design and development as well as guidelines to help ensure the highest possible quality objectives are followed.

**Inquiries section copy:**
Web standards are reviewed and updated as needed annually.  For inquiries about a standard or guideline, please open a new issue in our Github repository with relevant details about your question that will be directed to the Governance board.

**Comment by ljcarot** [comment]
@JennySanchez prior comment has updates to copy.  No change right now to blue message bar copy

**Comment by JennySanchez** [comment]
@ljcarot Below are the v1.1 design with the updates discussed. Please let me know if I missed anything. Thank you. 

![v1 1](https://user-images.githubusercontent.com/45213839/101684266-c0f1aa00-3a2b-11eb-8941-1961ee5bc2fc.jpg)

**Comment by ljcarot** [comment]
This looks great!!!  I might change order a bit of the cards but this is great for the review with Jo.

**Comment by wonilsuhibm** [comment]
Looking great. Thank you Jenny.

One thought—is the copy in the lead space a bit abrupt and strong?

Usually, the copy in the lead space should tell the visitor what it is. I do understand the need to make sure that people understand that these are requirements. How about something like this:

"These are IBM web standards that establish the required brand, technical, and legal compliance."

**Comment by JennySanchez** [comment]
@jeffchew @ljcarot 

👉 **Below is the latest design reviewed today. All the images and Sketch work files can be found on BOX with [this link](https://ibm.box.com/s/14gfpkrd6q3a01zmiz0heoln46rd45oj).**

![Screen Shot 2020-12-14 at 3.49.48 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/bd666a6b-dd4e-4091-a6a2-cbb0059f278d)

👉 **Here's the design with spacer for reference.**

![Updated design (v1.1) with spec.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/1c3740b9-1ed4-4632-9e0c-d2971541df32)


----

Jeff, A few reference findings to share with you.

- Please see the **[IBM Design website](https://www.ibm.com/design/)** for references and see if there is code we can leverage. Especially the Lead Space and Footer area. I believe we have the divider component already but you can find it on the IBM Design website as well.

![Screen Shot 2020-12-14 at 3.52.27 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/f7efe8b0-3333-482b-9a65-fe65030d79ea)

![Screen Shot 2020-12-14 at 3.41.18 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/95a8ebdb-46f9-4f03-8c8c-b94e6f86b463)

![Screen Shot 2020-12-14 at 3.41.35 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/180a48a3-e1be-4407-933f-bc4d2af540c3)


- For the checklist section, the component I used in the mock-up is called the Link Card in white theme. It's in the Gatsby Design Kit and I reached out to Diana, the Gatsby Design Kit designer on IDL Team, to get the code as we speak. I will follow up with you on that as soon as I heard from her. 

![Screen Shot 2020-12-14 at 3.42.41 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/03f3368d-773a-4408-8093-e81c345e2118)

- For the resources section, the component is a general Resource Card in white theme. You can find the code on the Gatsby website [here](https://gatsby-theme-carbon.now.sh/components/ResourceCard).
![Screen Shot 2020-12-14 at 3.45.26 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/74568a82-5b48-41b3-ba87-8679604091b7)

**Comment by JennySanchez** [comment]
By the way, I noticed the IBM Design Website Lead space has an [Anchor Link](url) feature! See it in action [here](https://www.ibm.com/design/teams/).
I don't think the homepage is long but in the future, if we like, we can utilize this feature, perhaps?
![Screen Shot 2020-12-14 at 4 09 36 PM](https://user-images.githubusercontent.com/45213839/102141702-e402cc00-3e26-11eb-99b3-653b5f7f0d66.png)

FYI: @wonilsuhibm

**Comment by JennySanchez** [comment]
@jeffchew Task issue [#791](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/791) created for the dev/coding work.

**Comment by JennySanchez** [comment]
@ljcarot Mike mentioned we should include the Brand experience guidelines as well and maybe give it a new section.

Per Mike, It would include

- https://www.ibm.com/brand/systems/watson/
- https://www.ibm.com/brand/systems/cloud/
- https://www.ibm.com/brand/systems/services/
- https://www.ibm.com/brand/systems/security/
- https://www.ibm.com/brand/systems/research/
- https://www.ibm.com/brand/systems/developer/
- https://www.ibm.com/brand/systems/it-infrastructure/
- Visual Systems for Hero brands and others

**Comment by ljcarot** [comment]
@JennySanchez what is the last bullet supposed to link to?

**Comment by JennySanchez** [comment]
@ljcarot I don't think it links to anything but just a general comment from Mike.

**Comment by wonilsuhibm** [comment]
@JennySanchez Here is the updated copy and visual:

"These are IBM web standards that establish excellence with the required brand, technical, and legal compliance."

<img width="1575" alt="Screen Shot 2020-12-17 at 10 27 10 AM" src="https://user-images.githubusercontent.com/30183447/102507642-7d61f600-4052-11eb-9f78-214f5e273c41.png">

**Comment by JennySanchez** [comment]
Work file and dev issue info updated.
![Screen Shot 2020-12-17 at 11 19 01 AM](https://user-images.githubusercontent.com/45213839/102520845-c36e8800-4059-11eb-83d2-8e018a914cac.png)
