### ISSUE TITLE
Website content crafting and publishing: (Components/Language Selector) - Target Jan 22

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom-website#760]
## Objective
Provide Carbon for IBM.com adopter the best practices and guidance they need to adopt Carbon for IBM.com.   The React version of this  component was made available from behind the feature flag and included in the ibm.com Library v1.12.0 release.  This work was managed under epic (#4048).  

This component was developed based on Knowledge Center needs.  The engineers made minor changes to the Footer Locale Selector.  The component can be seen in the React Canary environment.  https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-footer--default

## General publishing process
Please make sure you always start the content crafting process by viewing the **[2020 website content publishing process box document](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj)** first.

## Publishing for Components section website page
- Content crafting starts as soon as the design is finalized. 
- Components section includes UI components and Layout components.
- The content can be at the MVP level. MVP means the content meets the basic needs of an adopter for learning. It does not mean the content crafting will or should stop at this stage. Future enhancement should be working on with a separate task issue.
- MVP content publishing template and requirement can be found in the Publishing template and best practices/[_UI and Layout Components folder](https://ibm.box.com/s/8p9k496ohera4aa9zge9syxyehz5p7h0).
- Please use the visual and design spec files inside of the [Carbon for IBM.com Box folder](https://ibm.box.com/s/vo3u9mxn8y7a5d7zoqvrvz7aalbf2yu3) as a reference. 
- Content publishing to the live website can be code or markdowns. If you need guidance on how to start with markdowns, please see the step by step instruction in the [Editing and publishing in Github Box document](https://ibm.box.com/s/as8fo8gcecvizngxgq2dpuk4po2alq7t).
- When the page is published, please also make sure the components table list on the [Overview page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/overview) is updated as part of the publishing task.

## File naming and storage
- Name the Sketch file with the following convention: Name of the category + components/pattern/guideline + version. ex: Components-Feature card block v1.0, Guidelines-Expressive theme v1.0, Help-Overview v1.0 and etc.
- Please save all content publishing work files (box, markdowns link, or Sketch file) in the proper sub-folder under the[ ✍️ Content + Design folder](https://ibm.box.com/s/tty3jhshkt6l18jkn2v5ac2uznyjexns).

## Publishing acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done.
- [x] Page design is done (as needed).
- [x] Publishing with markdowns is done.
- [x] QA'd by Jenny.
- [x] Web page preview is approved by Linda, Jeff, and Wonil.
- [x] PR merged by Jenny.
- [x] Web page is published and live on the website.

**Comment by JennySanchez** [comment]
Through the study, I discovered the "Language selector" is behind a feature flag, and it's under Footer in Storybook (see screenshot below). 

![Screen Shot 2021-01-04 at 3.28.23 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/235c3562-7fac-4769-9451-3ad9a947d8ae)

Before the content crafting started, we need to find answers and agreed on the following items.

- Are we remove the feature flag?
- Should we add the Language selector information within each Footer variation on the current Footer page or should we give the Language selector its own website page and cross-linking to the Footer page?
- If we give it its own page, in order to not confuse the adopters when viewing Storybook, should we pull the Language selector out of the Footer and give it its own section in Storybook?

---

👉 01/04 Reached out to Jeff and Wonil via Slack for discussion and answers.

**Comment by RobertaJHahn** [comment]
@JennySanchez The language selector feature flag was removed.  The React dev issue:  (#4049) and the Web Components dev issue(#4706)

**Comment by JennySanchez** [comment]
Got it. @RobertaJHahn Thank you.

**Comment by JennySanchez** [comment]
**Task update:** V1 content draft shared with Wonil and Olivia for feedback.
![Language selector v1 0](https://user-images.githubusercontent.com/45213839/104389092-491e1000-5500-11eb-88db-2d6ae086a2c6.jpg)

**Comment by wonilsuhibm** [comment]
Overall looks good. One clarifying question: does changing to a different language change user preference and use that language next time the user visits the site?

**Comment by JennySanchez** [comment]
@wonilsuhibm Confirmed with Jeff - not language selector, just locale button/selector.

**Comment by JennySanchez** [comment]
PR merged and live on the website.
