### ISSUE TITLE
Code and update the IBM.com Web Standard website homepage:  Target Dec 30, 2020

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#791]
🚨 🚨 🚨  **Before the task priority is assigned, please check in with Linda to make sure the release target date is agreed by Jo Welsh, the project collaborator.** 🚨 🚨 🚨 

---

> As an IBM.com Web Standard adopter,

> I need a way to view all the required standards

> So that I know what requirements I need to meet and create the best user experience for IBM.com visitors.

#### Note

- This task is created for the coding development to update the [IBM.com Web Standard website](https://www.ibm.com/standards/web/) homepage.
- The design task detail can be viewed [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/748).
- The final design is attached below. All the images and Sketch work files can be found on BOX with [this link](https://ibm.box.com/s/14gfpkrd6q3a01zmiz0heoln46rd45oj).

![Screen Shot 2020-12-17 at 11 19 01 AM](https://user-images.githubusercontent.com/45213839/102520928-df722980-4059-11eb-9e28-d57fb05f762b.png)

#### Tasks

- [ ] Review the final design and understand the requirements with Jeff and Jenny
- [ ] Code the homepage according to the finalized design
- [ ] Share preview with Jenny for QA
- [ ] Update the design with code if needed
- [ ] Share the new homepage preview with DDS Leadership Team

#### Acceptance criteria

- [ ] New homepage design is released and live

**Comment by JennySanchez** [comment]
@jeffchew Assigning this task to you, for now, once we are ready, please let me know who on the dev team will work on the task so I can collaborate with the assignee.

**Comment by JennySanchez** [comment]
## Note for developer

For the checklist section (see screenshot below), the component used in the mock-up is called the "Link Card" in White Theme. It's a variation of the Resource Card component and the code for this component is currently `not` available.

![Screen Shot 2020-12-14 at 3.42.41 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/03f3368d-773a-4408-8093-e81c345e2118)

What we can do is...
1. Use the code for the Resource card (see code and usage guidance on Gatsby website [here](https://gatsby-theme-carbon.now.sh/components/ResourceCard/)) and do not add any left corner icon.

2. Utilize the code from other IDL ecosystem website and change the size to match our design. Websites we can check and utilize the code are the square cards on the [IBM Accessibility website/ Equal Access Toolkit page](https://www.ibm.com/able/toolkit/) (see screenshot below- image one) or the [IBM Accessibility website homepage page](https://www.ibm.com/able/toolkit/)/event section (see screenshot below- image two)

`image one`

![toolkit](https://user-images.githubusercontent.com/45213839/102402071-dfb2ec00-3fa9-11eb-9d95-a346df80728e.jpg)

`image two`

![event](https://user-images.githubusercontent.com/45213839/102402076-e0e41900-3fa9-11eb-9729-f9fa710374f3.jpg)

**Comment by JennySanchez** [comment]
**To developer: This is the FINALIZED copy for the Lead space.** (as 12/17/2020)

"These are IBM web standards that establish excellence with the required brand, technical, and legal compliance."

**Comment by jeffchew** [comment]
NOTE: the follow-on task for this after the new page is deployed is to remove the sub-pages from our production server, and open a ticket to webmaster team to purge akamai of the old pages.
