### ISSUE TITLE
Add the "Coming soon" images to new componet thumbnail view

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#794]
#### Objectives: 
We have a few new component thumbnail views currently without any image and it looks like a loading error (see screenshots below). 

![Screen Shot 2020-12-18 at 3.35.19 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/aa39927a-e277-4579-95db-93b130b9664c)

We need to add a "coming soon" image to them and also figure out how to set it up as the default, so in the future, if the image is not available yet, it can at least show as "coming soon".

![Screen Shot 2020-12-18 at 3.36.11 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/bf860651-404e-460d-9ba6-418467bccc7a)

#### Tasks:

`This task contains two parts:`

1. Add the "coming_soon.svg" (attached below) for the "Carousel" and "Leaving IBM" cards.
2. Set up the process for the gallery to automatically pull the "coming_soon.svg" image as the default whenever a new card is added. When using the "coming_soon.svg", the "hover" state should be disabled.

![coming_soon.svg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/adba9b8a-6c09-4a02-86f2-2c1a182b4442)

#### Acceptance criteria

- [x] The "coming_soon.svg" added to the "Carousel" and "Leaving IBM" cards and can be viewed on the live website.
- [x] The "coming_soon.svg" shows up on any new card added on the live website.
- [ ] Have a conversation with Jenny and help her understand how the automated process works
