### ISSUE TITLE
Audit and update the Components/Gallery view images - Target sprint 21-03

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#795]
#### Objectives

We need to make an audit for the SVG images currently used in the Gallery view to make sure the images are up to date and include the white background (the background of the component but not the background for artboard) so adopters can see the image still, even on the "hover" state.

(Correct setup example)
![Screen Shot 2020-12-20 at 3 33 50 PM](https://user-images.githubusercontent.com/45213839/102724970-e195eb80-42d8-11eb-9148-0714246dabfc.png)
![Screen Shot 2020-12-20 at 3 33 57 PM](https://user-images.githubusercontent.com/45213839/102724971-e2c71880-42d8-11eb-9927-211ac40288c0.png)

(Incorrect setup example - needs update)
![Screen Shot 2020-12-20 at 3 34 22 PM](https://user-images.githubusercontent.com/45213839/102724975-ece91700-42d8-11eb-847c-c52a2732a049.png)
![Screen Shot 2020-12-20 at 3 34 29 PM](https://user-images.githubusercontent.com/45213839/102724976-ed81ad80-42d8-11eb-99f7-fac17d7f3219.png)

**Note:** Jacob took the effort to update the image in October 2020 but it's not completed (view PR here).
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/704#issuecomment-747901106

#### Task:

- [x] Audit all the images
- [x] Update images with correct setup white background 
- [x] Export the images with the correct file name/format
- [ ] Schedule a work session with @annawen1 

#### Acceptance criteria

- [ ] The images correctly represent all the Carbon for IBM.com components
- [ ] Adopter can see the image with a white background on the hover state

**Comment by JennySanchez** [comment]
#794 task is related to the Gallery view image update as well.

**Comment by JennySanchez** [comment]
The initial audit and image updates are completed—schedule time to take a look with Anna tomorrow.

**Comment by JennySanchez** [comment]
👉 **Overall audit outcomes:**
![TableList.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/35ce86a9-b8ee-45f2-874d-609f267f8c32)
![Gallery.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/d53ebce0-c2bf-46ba-b7f6-30c76d774907)

👉 **All the updated SVGs can be found in this [BOX folder](https://ibm.box.com/s/xq7aqa339zywrzvrg6l6nk9n3e2fpv8e) (Updated thumbnails (02-08-2021)**

👉 **Audit Sketch work file can be found [here](https://ibm.box.com/s/8yrpqi59o9muaqxm78ydckfek1lro84k).**
![Screen Shot 2021-02-09 at 1 48 02 PM](https://user-images.githubusercontent.com/45213839/107419760-c5931700-6add-11eb-9774-5a2657debebc.png)
