### ISSUE TITLE
Craft and publish content for the Card section – with CTA:  Target Jan 22

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#805]
#### User Story

> As a Carbon for IBM.com adopter

> I need to see and learn all variations of a single component

> so that I can know what options I have to craft the best experience for IBM.com visitors

#### Note
James noticed the Card section page content is not up to date and the Card section – with CTA variation is missing from the page.

![Screen Shot 2021-01-05 at 4.36.56 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/625b7cb6-673e-47a8-9b4d-f3a169e55c44)

#### Tasks

- [ ] Craft the copy for the Card section – with CTA
- [ ] Create the reference image for the Card section – with CTA
- [ ] Update the website page content via Markdowns
- [ ] Add the anchor link and make sure it matches the section title
- [ ] Create PR
- [ ] Request review

#### Acceptance criteria

- [ ] Card section – with CTA content is added to the Card section page and live on the website

**Comment by JennySanchez** [comment]
Content draft created with markdowns and PR can be viewed [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/827).

**Comment by JennySanchez** [comment]
@wonilsuhibm Can you take a look and let me know if any edits needed via [Slack](https://cognitive-app.slack.com/archives/G01CFF8ETPU/p1611253565009700) or [PR 827](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/827)? Thank you.
