### ISSUE TITLE
Update Card Section and Card Section – with images page content

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#806]
#### User Story

> As a Carbon for IBM.com adopter

> I need to find information about a single component on the proper Carbon for IBM.com website page

> so that I won't be confused with the information presented on the website

#### Note
James noticed the Card section – with images content is included in the Card section page while there's a new website page titled Card section – with images.

#### Tasks

- [x] Remove the Card section – with images content from the Card section page (in markdowns).
- [x] Add the Card section – with images content to the Card section – with images website page (in markdowns).
- [x] Update the anchor link, intro copy, and section title to both pages (in markdowns).
- [x] Create PRs for review

#### Acceptance criteria

- [x] Both changes are reflected on the website live.

**Comment by JennySanchez** [comment]
Content update completed and can be viewed on the [live website](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/card-section-images).
