### ISSUE TITLE
10 Update the Express Theme website page images to meet IDL Aspect Ratio standard

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#816]
#### Objectives

We need to update the image set up (aspect ratio) on the [Expressive Theme page](https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/753/guidelines/expressive-theme/). Mike mentioned that not all the images on the website are following the IDL ratio best practices. This is an IDL violation.

📍 All the image need to follow the ratios listed below (actual content can be viewed on the IDL website [here](https://www.ibm.com/design/language/photography/tips-and-techniques#aspect-ratio))

![Screen Shot 2020-12-20 at 3.12.51 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/adfb59fe-0185-441d-99cb-f2d7a8d11290)

#### Task:

- [ ] Update all the images on the [Expressive Theme page](https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/753/guidelines/expressive-theme/).
- [ ] Create a list of findings (what works and what does not) to share with Mike for alignment.
- [ ] Share the finalized outcome with DDS Team members.

#### Acceptance criteria

- [ ] A list of finalized outcome share with the team members.
- [ ] About to start the Audit task via #797

**Comment by RobertaJHahn** [comment]
No longer needed.
