### ISSUE TITLE
Website content audit planning

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#860]
### Objective: 
Understand what we currently have on the website and make a plan on updating the website pages.

### Tasks:

- [ ] Take a look at all the website pages and update the Airtable inventory document.
- [ ] Make a plan on when to update what and who we should assign the update task.
- [ ] **More to add.**

### Acceptance 

- [ ] Task issues for the update are created and ready for prioritization.

**Comment by shixiedesign** [comment]
Content by section: 

## Guidelines 

### Layout foundations
https://ibm.box.com/s/1lm1zs6zcof4epd5k9i7wbk00o82glsj

### Type scale 

### Spacing scale 

### Type pairing

**Comment by shixiedesign** [comment]
### Images update: 
We need to do an audit and make a plan to update the images to meet IDL image ratio standards. [Jenny] - I might be pushing it.

### FAQ page
We need to update or add more FAQ questions to the website page.

**Comment by JennySanchez** [comment]
@shixiedesign The items you mentioned above are existed and have task issues to address them. The next step is for me to reset the priority so we can get started on them - FYI.

**Comment by JennySanchez** [comment]
We have individual task issues created to address the needs, and the website enhancement work (next gen) will be done in a later time. This task issue can be closed.
