### ISSUE TITLE
Website work prioritization planning

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#879]
### Objective:
We have many ideations, design research, content updates, and publishing task issue in the backlog, and we need to take a look at all the tasks we need to work on and look at the priorities and needs to make an execution plan for the works.

### Tasks:

- [x] Create a Mural board and list out all the tasks we need to do for the website.
- [x] Set prioritizes on the prioritizing grid.
- [x] Review the prioritizing grid outcome with @shixiedesign @ljcarot and @jeffchew 
- [x] Finalize the prioritization
- [x] Make sure all the task issues are ready for priority setting or start assigning process.

#### Acceptance criteria
- [x] A finalized priority list is ready for execution.
- [x] The website priority is shared with the DDS Team and stakeholders.
- [x] Task issues are created and ready to go (if needed).

**Comment by JennySanchez** [comment]
The [Mural board ](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1615215157517?sender=chsanche&key=38c4cb66-c300-4626-b733-8b2bcee40e29) set up completed and added all the task issues to the board for feedback.

![Screen Shot 2021-03-08 at 5.12.09 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/d9ddd4c7-f540-45a7-ba1b-f7eb21082282)

**Comment by JennySanchez** [comment]
**Task update:** 

- Reviewed the priorities with Linda and closed Epics and Task issues no longer relevant to the website work.
- Let Roberta knows about the closed Epics and Task issues so that she can update the Airtable document.

![Screen Shot 2021-03-19 at 4.21.12 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/475473a4-cb64-459d-8fe0-416642827796)

**Comment by JennySanchez** [comment]
Releases created and ready to be tagged to the Epics and Issues.

**Comment by JennySanchez** [comment]
All Epics and task issues were reviewed, and new Epcis and task issues were created. I will share the process document in the sprint demo and help Roberta update her Airtable document next Monday.
