### ISSUE TITLE
[Mega menu] Website - add Mega menu section to the Masthead website page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#897]
## Objective
Provide Carbon for IBM.com adopters the best practices and guidance they need to adopt Mega Menu.

## Publishing acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done.
- [x] Publishing with markdown is done.
- [x] Content review is done by DDS designers
- [x] Feedback is provide
- [ ] Revision is done and ready for QA
- [ ] QA'd by Jenny.
- [ ] PR merged by Jenny.
- [ ] Web page is published and live on the website.

## Note
[PR #889](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/889) created by Lily will be used for the work.

**Comment by JennySanchez** [comment]
**Task update:** Lily shared the initial content draft with Lila and I for feedback. After review,  we discussed and clarified a few questions we have, and Lily will work on the revision next.

**Comment by JennySanchez** [comment]
I followed with Lily today, and we are expecting to see the revision by EOD tomorrow. Once the content is finalized, we need to move into the markdown process.

FYI @RobertaJHahn This task might extend into Sprint 21-07.

**Comment by lily-kenney** [comment]
Image pull request: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/907

**Comment by lily-kenney** [comment]
Content pull request: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/909

**Comment by JennySanchez** [comment]
**Task update:** Review and Content and share the PR previews with DDS designers in Design Huddle for input.
A few styling updates for the Content and image from me and a few questions around variations come up.

**Next step:** I set up 30 minutes on Monday 03-30 9:30 am CT for Lily, Lila, Olvia, and myself to align on the variation usage to finalize the Content.

**Comment by JennySanchez** [comment]
Based on the discussion with Lila, Lily, and Olivia this morning. We recognized there are quite a few details we need to work on before we can confidently share the mega menu content contributed by Lily and Lila. For now, all the content will be stored in the BOX folder [here](https://ibm.box.com/s/lszqo3edc3tsr9rko4cw4dyhelob6s5n) (see screenshot below for what's in the folder). 

➜ **We will come back to it in a few sprints and finalize the content when we are ready.**
