### ISSUE TITLE
Website: [General] Document component usage logic for better adoption (section / block / group)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#903]
### Objective: 

We currently do not have any documentation to support adopters to learn more about a section, block, and group. To make sure the adopter and we speak the same language and create a better adoption experience, we need to make sure the information is crafted and shared. 

#### Additional information
- The follow-on work is included in issue (#1131)

### Tasks

- [ ] Research and find what currently the similar topic of content lives
- [ ] Review the possible location the content can be presented on the website
- [ ] Define what content detail we need to provide around the three areas

**Comment by JennySanchez** [comment]
FYI: @shixiedesign FYI on this task existed, and let's discuss in the DDS Design huddle on Friday

**Comment by JennySanchez** [comment]
@shixiedesign Any new updates on the content crafting?

**Comment by RobertaJHahn** [comment]
@DragosRistici Are you working on this?

cc:  @shixiedesign

**Comment by DragosRistici** [comment]
@RobertaJHahn Yes. Working on the content. Had also talks about it with Jan. We are in a good place.

**Comment by DragosRistici** [comment]
The file was added here [in this Box folder](https://ibm.box.com/s/787hhson3me1jd1k1tg4czpqre83ooab).
