### ISSUE TITLE
Website [Components Overview Page] Table view links treatment designs

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#908]
### Objective: 

We spot the challenge to complete all the components publishing issues currently in the backlog and figure out how not to publish any pages that are not meeting the MVP version criteria.

At the same time, to support adopter needs, we need to at least able to provide the status of a component and links to the design spec, functional spec, and storybook links treatments on the Components overview page the content publishing is in work.

### Task:

- [x] Work on design explorations on how we can showcase the links on the table list
- [x] Review the designs with DDS designers and Jeff for feedback
- [x] Finalize the design

### Acceptance criteria

- [x] A dev task issue created for implementation to be done in the following sprint

**Comment by JennySanchez** [comment]
**Task update:** A few initial ideas to share with Jeff tomorrow to find out if any of them are not doable with the codebase will get feedback from the rest of the team.
![Screen Shot 2021-04-05 at 4 16 23 PM](https://user-images.githubusercontent.com/45213839/113629702-63154d80-962c-11eb-8da0-9ce99227ca28.png)
![Screen Shot 2021-04-05 at 4 16 44 PM](https://user-images.githubusercontent.com/45213839/113629710-64df1100-962c-11eb-8b39-d7f53fa63789.png)

**Comment by JennySanchez** [comment]
**Revised design for round two feedback**
Shared with Linda, Shixie, and Jeff via Slack today

`Note:`

- Back to top, CTA, and Dotcom shell: For the component scenario, content published, the design spec files, and storybooks are available to adopters.

- Button group: For the component scenario, content is not published, but the design spec files and storybooks are available to adopters.

- Card: For the component scenario, content, design spec files, and storybooks are all unavailable to adopters.

![Screen Shot 2021-04-07 at 4.43.11 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/33e720cb-f61e-4bf6-b308-ec44d31855d3)

**Comment by JennySanchez** [comment]
**Based on the DDS leaders and designer feedback, we will move forward with Option B.**

![Screen Shot 2021-04-15 at 10.52.14 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/00ba8ee4-2176-4a97-8232-11b490620972)

**Comment by JennySanchez** [comment]
[Dev issue #938](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/938) created for the implementation work in Sprint 21-09
