### ISSUE TITLE
Website inventory Airtable document clean up

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#916]
## Objective:

We need a way to see the inventory of the website pages. This is the current Airtable document we are using.   https://airtable.com/tblscN2O3bsvY5DvD/viwAO734OqRV9bbrR?blocks=hide

## Steps:

- [ ] ~Talk to Roberta and see how this document is utilized in her workflow~
- [ ] ~Add or delete columns and features~
- [ ] ~Set cadences to update the document~
- [ ] ~Share the updated form with the team~

**Comment by JennySanchez** [comment]
**Note:** Exploring different ways to record the inventory without too many steps or maintaining.

**Comment by JennySanchez** [comment]
**Task update:** Revisit the purpose of the website inventory list and if Airtable is the best tool for the inventory list creation. Explore new ways to make sure the list can be easily found and maintained with up-to-date information.

**Comment by JennySanchez** [comment]
The new inventory list will no longer maintain with the Airtable. Task [#1045](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom-website/1045) was created for creating the new list.

FYI: @RobertaJHahn
