### ISSUE TITLE
Website [All about Carbon for IBM.com] What is Carbon for IBM.com?

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#923]
### Objective:

- Through Slack channel and adopter conversation, adopters need to understand Carbon and Carbon's differences for IBM.com. Some high-level information is currently share on the Get started website page, and we might need to provide more detail to help adopters gain a clear understanding of the two design systems.

- I also noticed the page title "Get started" is not appropriately structured on the left navigation, and we need to update it.

### Task types

- Craft and publish new content on a new website page
- Update website left nav labels on the website

### Steps

- [x] Create initial content with markdowns
- [x] Share the PR preview link with @ljcarot for review
- [x] Finalize the content
- [x] PR review is done
- [x] PR is merged

### Acceptance criteria (The meaning of "Done")
- [x] Updates or new Content is showing up on the live website.

**Comment by JennySanchez** [comment]
**Note:** Based on the sprint demo feedback, we need to update the content on this page and release it after the Carbon Design Team does the expressive theme items.

**Comment by RobertaJHahn** [comment]
@JennySanchez I'll leave the issue in this sprint and move it to the correct sprint after we find out when Carbon will release the expressive theme items.  You may be able to begin crafting the content, based on Olivia's analysis.

cc:  @oliviaflory

**Comment by JennySanchez** [comment]
The latest content can be viewed via the [preview link](https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/922/index.html).

@oliviaflory Please let me know what edits we need to make to reflect the changes.

**Comment by JennySanchez** [comment]
Per Linda via Slack, we will have a team discussion in our next Team Huddle (next Thursday) to discuss a team.

**Discussion: Opening link guideline**
(Draft content: https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/943/guidelines/opening-link/) 

- When to open a link in a new tab, when to display the leaving IBM pop-up, and when to open in a new tab?
- Should it be combined with the page layout design standard page on W3?

**Comment by oliviaflory** [comment]
@JennySanchez @shixiedesign making comments based on what is written in the current PR. But I think we need to consider when we will be transitioning away from the Expressive theme and the communications around that as well. Or more simply, acknowledging the transition time?

---

_I think we should lead with What is Carbon section, it makes more sense to establish that Carbon is IBM's design system and then continue to explain how Carbon for IBM.com leverages Carbon as the foundation and adds on for IBM.com experiences._

> ### What is Carbon?
Carbon Design System, (or simply Carbon), represents a way to implement the IBM Design Language across IBM products. Choosing Carbon as the strategic solution for Carbon for IBM.com ensures IBM has one consolidated design system across product and web. Carbon for IBM.com works alongside Carbon to produce themes, components, patterns, and guidelines to leverage IDL for IBM.com’s more expressive nature.

*Thinking we shouldn't change how Carbon talks about itself, so pulled their copy and combined some of your writing*

### What is Carbon?
Carbon Design System, (or simply Carbon), is IBM’s open source design system for products and digital experiences. With the IBM Design Language as its foundation, the system consists of working code, design tools and resources, human interface guidelines, and a vibrant community of contributors.

----

> ### What is Carbon for IBM.com?
As IBM.com’s official design system, Carbon for IBM.com serves a wide range of designers and developers that are building digital products and experiences.
Carbon for IBM.com is building for the IBM.com maker’s business needs. It also means we have a brilliant team of engineers and designers working full time to help make IBM.com better. It is maintained by the Digital Design Squad, a core team of designers, developers, and writers.
The goals of the Carbon for IBM.com include improving visual consistency and quality for all IBM.com website pages, establishing a shared user-centered experience for all IBM.com visitors, and providing clear, discoverable guidance around design and development best practices to all Carbon for IBM.com adopters.

### What is Carbon for IBM.com?

Carbon for IBM.com is built with Carbon at its foundation, with additional components and styling optimized for reading and the expressive nature of IBM.com's editorial experiences, and serves a wide range of designers and developers that are building digital products and experiences. Choosing Carbon as the strategic solution for Carbon for IBM.com ensures IBM has one consolidated design system across product and web. Carbon for IBM.com works alongside Carbon to produce components, patterns, and guidelines to leverage the IBM Design Language for IBM.com’s more expressive nature.

Carbon for IBM.com is building for the IBM.com maker’s business needs. It also means we have a brilliant team of engineers and designers working full time to help make IBM.com better. It is maintained by the Digital Design Squad, a core team of designers, developers, and writers.

The goals of the Carbon for IBM.com include improving visual consistency and quality for all IBM.com website pages, establishing a shared user-centered experience for all IBM.com visitors, and providing clear, discoverable guidance around design and development best practices to all Carbon for IBM.com adopters.


---

> ### What are the key differences between Carbon and Carbon for IBM.com?

> Carbon for IBM.com is for IBM.com experience. The Carbon Design System is for product experience.

> Carbon for IBM.com adopters are the IBM.com website’s page makers. The Carbon Design System adopters are the IBM product teams.

> Carbon for IBM.com is built with React and Web Components. The Carbon Design System is built with React first and supports core parts of the system in Vanilla JS, Angular, Vue, and Svelte.

> Carbon for IBM.com adopters craft IBM.com experiences by using the Carbon Expressive kit. Carbon adopters craft product experiences by using the Carbon kit.

> Carbon for IBM.com is developed and maintained by the Digital Design Squad. The Carbon Design System is developed and maintained by the Carbon Design System team.

The Carbon Design System is for product and web experiences, and is the foundation for Carbon for IBM.com.

Carbon for IBM.com provides layout components that are more expressive and ... *feel a bit stuck on how to phrase layout components*

Carbon for IBM.com adopters are the IBM.com website’s page makers. The Carbon Design System adopters are the IBM product teams.
*Note: technically Carbon for IBM.com adopters are also using the Carbon Design system. I don't think this piece makes sense to include..but curious to hear other people's thoughts*

Carbon for IBM.com is built with Web Components and React. The Carbon Design System is built with React first and supports core parts of the system in Vanilla JS, Angular, Vue, and Svelte.
*Note: I flipped Web Components and React here because I think we are building in Web components first*

Carbon for IBM.com adopters craft IBM.com experiences by using the Carbon Design System kit (link?) and the Carbon for IBM.com layout components (link?). Carbon adopters craft product experiences by using the Carbon Design System kit.
*Note: with the change to the expressive theme implementation, the IBM.com adopters will use the Carbon Design System kit because the expressive variations will be included*

Carbon for IBM.com is developed and maintained by the Digital Design Squad. The Carbon Design System is developed and maintained by the Carbon Design System team.

--- 
### *With the expressive theme integration our two teams are almost more similar than different. I wonder if we need to rethink the key differences section a little bit and consider that **BOTH** product and website designers will use Carbon Design System kit, but web designers have more pre-configured or pre-designed components to choose from with the layout components.*

The key differences are the **Typography** and the **Layout components** that Carbon for IBM.com team provides for our adopters

- Both product and IBM.com makers will use the Carbon Design System UI components.
- Carbon product adopters utilize the Productive type sets
- Carbon for IBM.com utilize the Expressive type sets.
- Carbon for IBM.com makers will utilize the larger body size and expressive component variations in their work to maintain the hierarchy for reading experiences
- Carbon for IBM.com provides layout components that are pre-configured to for the grid in order to maintain a more consistent visual language across all experiences on IBM.com

**Comment by JennySanchez** [comment]
@oliviaflory 

>  Agreed with you on we need to consider when we will be transitioning away from the Expressive Theme. This might be a good follow-up conversation to have in the Big Carbon meeting.

I am fine with the "What is Carbon?" section stay as the first section on the page but not removing it or link it. Because without the section, it lost the purpose of able adopters to compare to have some high-level learning around the differences of the two.

"Carbon for IBM.com provides layout components that are more expressive and ..."
> We do not just provide layout components tho. 

"Carbon for IBM.com adopters are the IBM.com website's page makers. The Carbon Design System adopters are the IBM product teams."
> Agree with you. Technically, Carbon for IBM.com adopters are also using the Carbon Design system, but the key here is to address the adopter's groups are two different types in a simple sentence.

"Carbon for IBM.com is built with Web Components and React. You flipped Web Components first because we are building in Web components first."
> Good thinking!

" With the changes, The Carbon Design System kit will be the only kit adopters need"
> Yes.


**The rest of the edits look great. Thank you for taking a look, Olivia!**

**Comment by JennySanchez** [comment]
Task completed.
