### ISSUE TITLE
Website [CTA] Add when to open new windows and tabs best pracrice

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#926]
### Objective:

Adopters are looking for guidance on opening new windows and tabs from a link when setting uplinks. The tip is not currently available on the website, and we need to guide to support the adopter's need.

### Task:

- [ ] Research on if we have existing guidance for IBM.com 
- [ ] Decide if we need to add the content as a link or craft content for it.
- [ ] Finalize the content with markdowns

### Acceptance criteria

- [ ] New information shows up on the CTA Components website page, ready for Adopters.

**Comment by JennySanchez** [comment]
**Finding from @photodow** 
https://www.w3.org/TR/WCAG20-TECHS/G200.html

**Comment by JennySanchez** [comment]
I reached out to Jo to find out if she has any resources to share today.

**Comment by JennySanchez** [comment]
**From Anna on the Carbon Team - NNG has a good article about it.**
https://www.nngroup.com/articles/new-browser-windows-and-tabs/

**Comment by photodow** [comment]
One point I don't know if I've seen in some of the links listed is when we add a link with a target to open in a new window/tab we are forcing that user to open that link in a new window/tab. Vs. if we don't apply that target then the user now has the choice. Some people like it, some people don't.

**Comment by JennySanchez** [comment]
I reached out to Jo W., and she mentioned she is not aware of any documentation around this topic.

**Comment by JennySanchez** [comment]
Box document created for the content crafting and can be viewed [here](https://ibm.box.com/s/yjmzn19o7w9upotqnbd8nfk6cx6f22sd).

**Comment by JennySanchez** [comment]
**Note:** Updated the content format and take the Mobile and Tablet information off based on the feedback received from Mike and the Carbon Team today.

**Comment by JennySanchez** [comment]
**Task update:** Shared the updated content with Jo and DDS Team for feedback.

**Comment by JennySanchez** [comment]
Per Linda via Slack, we will have a team discussion in our next Team Huddle (next Thursday) to discuss a team.

**Discussion: Opening link guideline**
(Draft content: https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/943/guidelines/opening-link/) 

- When to open a link in a new tab, when to display the leaving IBM pop-up, and when to open in a new tab?
- Should it be combined with the page layout design standard page on W3?

**Comment by JennySanchez** [comment]
Followed up with Linda, and the links shared by her for reference listed below:

- https://www.ibm.com/standards/web/v19a-archive/components/external-link/
- https://www.ibm.com/standards/web/

**Comment by JennySanchez** [comment]
@ljcarot The latest content is [in the PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/943) and can be viewed via [preview link.](https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/943/guidelines/opening-link)

**Comment by JennySanchez** [comment]
**Task update:**

- The latest content is on the W3 page. 
![Screen Shot 2021-05-05 at 2 26 16 PM](https://user-images.githubusercontent.com/45213839/117217382-ed390900-adc6-11eb-99d3-f08c2847d91d.png)

- DDS Lead discussion call moved to Friday.

**Comment by JennySanchez** [comment]
**Task status update:** Content lived on the W3 page, and PR for the Carbon for IBM.com website will be closed.
