### ISSUE TITLE
Website [Components Overview Page] Table view links treatment update

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#938]
### Objective: 

We spot the challenge to complete all the components publishing issues currently in the backlog and figure out how not to publish any pages that are not meeting the MVP version criteria.

At the same time, to support adopter needs, we need to at least able to provide the status of a component and links to the design spec, functional spec, and storybook links treatments on the Components overview page the content publishing is in work.

### Task:

- [ ] Update the table list view based on the design provided below with code.
- [ ] Review the PR with Jenny

![Screen Shot 2021-04-15 at 10 52 14 AM](https://user-images.githubusercontent.com/45213839/114902200-33f49e00-9ddb-11eb-8229-16a188bfd2ab.png)
![Screen Shot 2021-04-15 at 10 59 54 AM](https://user-images.githubusercontent.com/45213839/114902211-36ef8e80-9ddb-11eb-9b09-ef7d109fc3e2.png)

### Acceptance criteria

- [ ] Newly updated table list view design live on the website

**Comment by JennySanchez** [comment]
**Task items mentioned by Jeff:** To update the Data File, publish with the current link on the components website page, update the components overview page to include the design changes.

**Comment by RobertaJHahn** [comment]
No longer needed.  Closing
