### ISSUE TITLE
Website [Training session recording] Add links to the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#939]
#### Objective:

Carbon for IBM.com adopters need a way to watch the available training session recordings, so they can learn how to adopter Carbon for IBM.com and use the resources DDS provides.

#### Task:

- [x] Meet with Jeff to define what we need to add to the website
- [ ] ~Make sure the BOX folder where we save the recording are accessible to the adopters~
- [x] Decide where we should add the links on the website (Designing and Developing website pages and Resource page)
- [x] Craft the paragraph/content for adding the link if needed
- [x] Publish via markdown/PR

#### Acceptance criteria

- [ ] Links are available to adopters on the live website.

**Comment by JennySanchez** [comment]
Thoughts for discussion with Jeff on 05/03.

- Page title: Tutorials
- Update the "Designing" and "Developing" from a page to a category.
- Add "Tutorials" to each category.
- We will add the "Resource" page to the section in a few sprints, so this works out for the AI update vision.

---

**Designing**
The tutorials will help you start designing with the Expressive Kit and teach you about some of the foundational pieces of the design system.

- (format: cards)
- Carbon foundations
- Design resources / Expressive Kit
- Using the design system and making it better / Contribution

**Developing**
The tutorials will guide you in creating React and Web components apps with the Carbon for IBM.com. We'll teach you the ins and outs of using Carbon for IBM.com components while introducing web development best practices along the way.

(format: cards)

- Deep dive on React
- Deep dive on Web components
- Contributing to Carbon for IBM.com

---
note: https://ibm.ent.box.com/s/y7mxrjiqc2o61qggsdmawuxaegd65tmt/folder/130557764698

**Comment by JennySanchez** [comment]
Based on the discussion with Jeff. We are aligned and will set up the training to go to the [Your Learning Digital Design Summit 2021 Webinar Series page](https://ec.yourlearning.ibm.com/w3/series/10148614?layout=grid).
