### ISSUE TITLE
Website [Components website pages] update the sentence under the Design and functional specifications section

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#948]
### Objective:

We need to update the sentence under the Based on the Design and functional specifications section across the website pages in the Components section, so the text link set up can meet the accessibility standard.

👉 Based on the discussion on Slack, we will update the sentence to be:
**For more details, `see design and functional specs` (link).**

### Task

- [x] Make the update on all Components pages (a total of 46 pages) with a PR
- [x] PR reviewed and merged

### Acceptance criteria

- [x] All Components website Design and functional specifications section have the same sentence live on the website.

**Comment by JennySanchez** [comment]
Go over and updated all the website pages under the Components category.

- Make sure all the sentences under the Design and functional specifications section are unified.
- Make sure all the links to the Design and functional specifications section are linked correctly.
- Adjust the spacing between each section on the website page are all the same.

👉 [PR created](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/990).

**Comment by JennySanchez** [comment]
Updates completed and live on the website.
