### ISSUE TITLE
Website [Link list] Add variation information and images to the website page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#949]
### Objective:

**We currently do not have all the variations included in the Link list website page.**

👉 What's in the [Web Components Storybook](http://ibmdotcom-web-components.mybluemix.net/?path=/story/components-link-list--default)

![Screen Shot 2021-04-20 at 10.40.37 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/a4dd220c-ad3e-4f0c-8f42-6e5b8466c7c5)))

👉 What's on the [live website](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/link-list))
![Screenshot_2021-04-20 Carbon for IBM com.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/6bf374ab-cae5-4618-9dc1-ba62f54daea0)

### Task

- [ ] Craft content for the variations
- [ ] Create images for the variations
- [ ] Add the images and content via Markdowns
- [ ] Review with designers
- [ ] Finalize the content

### Acceptance criteria

- [ ] Variations are published on the Link list page and live on the website

**Comment by JennySanchez** [comment]
Double-check with designers and Shixie. We do not need to update the Link list website page at the moment. This issue will be closed.
