### ISSUE TITLE
Website [Dev question] Is there a limit on how many pages we can have for the Components section?

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#954]
### Problem

@shixiedesign mentioned she could not see some of the component website pages while adding new pages. Her suspension is there might be a cap for the website pages can be created per category, but we are not 100% sure if that's the reason.

**See [PR 953 preview link](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/953) for the problem describe.**

![Screen Shot 2021-04-26 at 11 45 36 AM](https://user-images.githubusercontent.com/45213839/116120220-eef72400-a684-11eb-997c-439a3c73799b.png)
![image](https://user-images.githubusercontent.com/45213839/116120227-f0c0e780-a684-11eb-9685-6491c180d940.png)

### Task:

- [ ] Dev looks at the code and lets Shixie and Jenny know if there's a cap for website pages to be created per category.
- [ ] Dev will work with Shixie to fix the website page not showing up if the answer is no.

### Acceptance criteria

- [ ] Components website page Shixie is working on show up in the PR
- [ ] Shixie and Jenny know what caused the website pages to not showing up

**Comment by JennySanchez** [comment]
@jeffchew @RobertaJHahn The priority is set at High bc. This is a blocker for website content publishing.

**Comment by JennySanchez** [comment]
FYI: I reached out to the Carbon Gatsby Team but have not heard anything back yet.
<img width="424" alt="Screen Shot 2021-04-26 at 11 31 48 AM" src="https://user-images.githubusercontent.com/45213839/116119213-cc184000-a683-11eb-86e0-686d27ef66ea.png">
