### ISSUE TITLE
Website [Components Overview/Gallery] Create thumbnail illustrations 

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#957]
### Objective

Shixie created content for the following pages, and the overview pages need to include the following component information for both the Table list view and Gallery view.

- Card in card
- Carousel
- Content group – banner
- Tab extended
- Tab extended with media

### Task

- [x] Add the descriptions and links of the new components to the Table list 
- [x] Add the new components thumbnail illustrations to the Gallery view
- [x] Create PR and review with designers
- [x] Finalize the designs

### Acceptance criteria

- [ ] New information and illustrations are live on the website

**Comment by JennySanchez** [comment]
[PR opened.](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/964)
