### ISSUE TITLE
Website [Content guidance/Content model] Learning and working session with Michael F.

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#960]
### Objective:

Understand the current Content guidance structure and the work process from Michael F.

### Task

- [x] Schedule time with Michael for the learning and working sessions
- [ ] ~Work and publish at least two content models together~

### Acceptance criteria

- [ ] ~Jenny can work and publish Content guidance confidently.~

**Comment by JennySanchez** [comment]
FYI @ljcarot @RobertaJHahn

**Comment by JennySanchez** [comment]
Kick-off meeting scheduled for Tue 05/04/2021 11:00 am CT

**Comment by JennySanchez** [comment]
I met with Michael yesterday and learned more about the Content style model work process at a very high level.

@RobertaJHahn @ljcarot and I regrouped, and the conversation outcome is that we will no longer need to proceed with this training. The Afterburner team will continue the Content style work.
